### ISSUE TITLE
gerrit.coffee do not use/parse full sshUrl spec and fails if we specify username

### ISSUE THREAD

**Issue by renoirb** [github/hubot-scripts#1011]
## Problem
1. The documentation block is not clear about the format to use on the sshUrl
2. During the execution, while conneting to the remote, there is now way to know what credendials were used to connect, only says ("Permission denied (publickey).")

```
[Sun Jul 07 2013 05:04:07 GMT+0000 (UTC)] INFO Gerrit stream-events: Starting connection
[Sun Jul 07 2013 05:04:07 GMT+0000 (UTC)] INFO Gerrit stream-events: Permission denied (publickey).

[Sun Jul 07 2013 05:04:07 GMT+0000 (UTC)] INFO Gerrit stream-events: Connection lost (rc=255)
[Sun Jul 07 2013 05:04:08 GMT+0000 (UTC)] INFO Gerrit stream-events: Starting connection
[Sun Jul 07 2013 05:04:08 GMT+0000 (UTC)] INFO Gerrit stream-events: Permission denied (publickey).

[Sun Jul 07 2013 05:04:08 GMT+0000 (UTC)] INFO Gerrit stream-events: Connection lost (rc=255)
```
## Suggestion
1. Use `ssh2` npm module and 
2. support full ssh url spec or allow other configuration through shell variables

**Comment by orieg** [comment]
I will try to package it next week. I added a quick fix for the auth url. Not pretty tho.

https://github.com/orieg/hubot-gerrit
