### ISSUE TITLE
IMPORTANT: No longer accepting new scripts to this package, create external packages instead

### ISSUE THREAD

**Issue by tombell** [github/hubot-scripts#1113]
Please read https://github.com/github/hubot-scripts/blob/master/CONTRIBUTING.md if you're submitting a pull request for a new script, but basically new scripts aren't accepted.

We recommend hubot script packages now. ~~Please check out the [hubot-scripts](https://github.com/hubot-scripts) organization for more details.~~

~~Once you've created a repository, you can file an issue against [hubot-scripts/packages](https://github.com/hubot-scripts/packages) to have it forked to hubot-scripts, as well as to be added to the organization in order to maintain the fork.~~

See https://github.com/github/hubot-scripts/issues/1641 for current efforts to find extractions of scripts in this repository for npm packages

*_Edit by @technicalpickles 2016-05-06:_ cross out out of date info, link to most recent deprecation efforts

**Comment by juanbrujo** [comment]
How to handle API-KEY's when a script is required in hubot-scripts.json? brewerydb.coffee needs API key but where I can define it? as a global variable somewhere in hubot?

**Comment by MrKeiKun** [comment]
Hi how to load customize hubot-script now?
like before you can just put `.coffee` file inside `myhubot/scripts/`
then enable it via adding the file to `hubot-scripts.json`
But now, I tried doing it, it failed.

**Comment by patcon** [comment]
Hi @MrKeiKun! I'm not using hubot right now, but fwiw, github (and issue tracker) etiquette is to open a new issue for questions and comments not directly related to the issue topic (in this case: the org "No longer accepting new scripts to this package")

You should probably create a new one :) (ping me in the issue, and I'll try to help you troubleshoot)
