### ISSUE TITLE
jenkins-notifier.coffee is broken

### ISSUE THREAD

**Issue by pascaldevink** [github/hubot-scripts#1160]
It seems either the Jenkins Notification plugin or something else was updated, as the script does not work anymore.
The following error occurs:
```
jenkins-notify error: TypeError: Cannot read property 'phase' of undefined. Data: [object Object]
```
I'm using the following versions:
Jenkins: 1.533
Jenkins Notification plugin: 1.5
Hubot: 2.6.3
Hubot scripts: 2.5.6

It seems that the JSON body send by Jenkins is not available in the req.body var. Don't know how or why though. Perhaps @spajus knows more?

**Comment by tholu** [comment]
@Freyskeyd How did you get it to work? Your script is missing unfortunately.

**Comment by halkeye** [comment]
@tholu Kinda late notice, but do you want to try https://www.npmjs.com/package/hubot-jenkins-notifier

**Comment by tholu** [comment]
@halkeye I actually did and got it working!

**Comment by halkeye** [comment]
@technicalpickles can we close this then?
