### ISSUE TITLE
API endpoint used in cumberbatch deprecated

### ISSUE THREAD

**Issue by doublejosh** [github/hubot-scripts#1541]
Just an FYI that this script does not function anymore due to Twitter update.

https://github.com/github/hubot-scripts/blob/master/src/scripts/cumberbatch.coffee

**Comment by technicalpickles** [comment]
We are actually moving away from adding scripts to repository in favor of separate npm packages per scripts. We have already stopped accepting new scripts, and will stop accepting pull requests on this repository after hubot 3.0.

See #1113 for details. If you are interested in maintaining this longer term, check npm in case someone already made a package for it, and if not, check out https://hubot.github.com/docs/scripting/ for creating a package of your own.

cc @froots as the original script author
