### ISSUE TITLE
Problem with msg.http (in teamcity plugin)

### ISSUE THREAD

**Issue by Fandekasp** [github/hubot-scripts#1548]
The teamcity plugin doesn't work for me. When a method is called, I can send debug messages up to the msg.http().headers().get() method, and it doesn't call the callback after this.

Since my teamcity server is using https, and a curl request using the same headers and url would not work without the -k or --insecure option (and works fine with -k), I'm wondering if there is an SSL certificate verification somewhere in msg.http.get ?

Or do you have another idea? How would you debug this? 

Thanks for your help in advance
Cordially

**Comment by technicalpickles** [comment]
We are actually moving away from adding scripts to repository in favor of separate npm packages per scripts. We have already stopped accepting new scripts, and will stop accepting pull requests on this repository after hubot 3.0.

See #1113 for details. If you are interested in maintaining this longer term, check npm in case someone already made a package for it, and if not, check out https://hubot.github.com/docs/scripting/ for creating a package of your own.
