### ISSUE TITLE
gitlab: Only the first line is prefixed

### ISSUE THREAD

**Issue by ZeissS** [github/hubot-scripts#1557]
https://github.com/github/hubot-scripts/blob/master/src/scripts/gitlab.coffee#L95

If the `description` consists of multiple lines, only the first line will get prefixed with the `>>`. This leads to incorrect messages send to the chat (in our case: irc).

Expectation: Each line should be prefixed.

**Comment by technicalpickles** [comment]
This repository has been deprecated for awhile in favor of npm packages. It looks like this one was extracted to https://github.com/spruce/hubot-gitlab-hooks so I'd give that a try to see if it works any better. We are in the process of finding scripts that have been extracted, and deprecating them over in #1641
