### ISSUE TITLE
calling several scripts

### ISSUE THREAD

**Issue by Fandekasp** [github/hubot-scripts#1559]
I tried the following (! alias to hubot)

    > !when you hear weatherReport do weather me Osaka
    > !when you hear weatherReport do satellite me Osaka
    > !new job 0 9 * * 1-5 "Daily report: weatherReport"

Using Eardropping and Wunderground from hubot-scripts, as well as hubot-cron, I'd like hubot to send everyday the weather.

Another idea I had that didn't work either would be something like:

    > !new job 0 9 * * 1-5 " Daily report:\n!weather me Osaka\n!satellite me Osaka"

Since Hubot won't listen to itself, or recognize multiple commands in one string, the weather fails to show up after the cron is executed. Is there any way to do what I want ? How would you proceed ?

Thanks for your advices

**Comment by technicalpickles** [comment]
Closing this since there's a discussion over in https://github.com/miyagawa/hubot-cron/issues/12
