### ISSUE TITLE
graphite.coffee not returning results?

### ISSUE THREAD

**Issue by jmreicha** [github/hubot-scripts#1564]
After adding `graphite.coffee` to hubot-scripts.json and deploying, I am seeing options for interacting with graphite but when I enter the command `graphite list` hubot returns nothing.  We are using slack, if it matters.

I have added

```
GRAPHITE_URL <url>
GRAPHITE_PORT <port>
```

Not sure where to look for clues to what's going on?  The logs on the hubot server are just showing requests happening.  Any ideas?

Just wanted to add an update to this.  At first it was a firewall issue, requests were not reaching graphite, so I fixed that but now I can see requests coming in to the web server, there are just no results being returned.  Here are some of the GET's I see in the access logs.

```
x.x.x.x - - [26/Aug/2014:08:54:21 -0700] "GET /browser/usergraph/?query=*&format=treejson&contexts=1&path=&node= HTTP/1.1" 200 95
x.x.x.x - - [26/Aug/2014:08:54:33 -0700] "GET /browser/usergraph/?query=*&format=treejson&contexts=1&path=&node= HTTP/1.1" 200 95
x.x.x.x - - [26/Aug/2014:08:56:30 -0700] "GET /browser/usergraph/?query=*&format=treejson&contexts=1&path=&node= HTTP/1.1" 200 95

**Comment by technicalpickles** [comment]
We are in the [process of deprecating this repository](https://github.com/github/hubot-scripts/issues/1641). We're not accepting any changes or fixing any issues unless it furthers that end. There isn't currently a hubot-graphite package outside of this, so there's not a lot else I can suggest at this time.
