### ISSUE TITLE
Hubot Page Load Time?

### ISSUE THREAD

**Issue by FinalTrigger** [github/hubot-scripts#1584]
How can I get my hubot to tell me how long it takes for a page to load?

example: @hubot page load time http://www.google.com

**Comment by technicalpickles** [comment]
We are actually moving away from adding scripts to repository in favor of separate npm packages per scripts. We have already stopped accepting new scripts, and will stop accepting pull requests on this repository after hubot 3.0.

See #1113 for details. If you are interested in making a script for this and maintaining this longer term, check npm in case someone already made a package for it, and if not, check out https://hubot.github.com/docs/scripting/ for creating a package of your own.
