### ISSUE TITLE
Hi im new to git so im not sure how to suggest a change but here it is

### ISSUE THREAD

**Issue by ileathan** [github/hubot-scripts#1588]
the file google.coffee does not work for me because it returns a URIencoded form of the link.

When i change the line msg.send url

to

msg.send decodeURIComponent url 

It works as expected.

**Comment by technicalpickles** [comment]
This repository has been [deprecated](https://github.com/github/hubot-scripts/issues/1113) for awhile in favor of npm packages, and it looks like this one was extracted to https://github.com/mnpk/hubot-google. We are in the process of finding scripts that have been extracted, and deprecating them over in https://github.com/github/hubot-scripts/issues/1641, so I'd give that a try to see if it works any better.
