### ISSUE TITLE
zoidberg "you should feel bad" meme displays hubot name on meme

### ISSUE THREAD

**Issue by meetmagdalene** [github/hubot-scripts#1596]
I just connected up the futurama.coffee script to my hipchat hubot, but whenever it calls and makes a meme with any of the commands it adds the hubot's name to the beginning like `Cortana: Your beer is bad and you should feel bad!`

I don't know much about coffee script so I can't pick out how to remove that from the meme generation. Any thoughts? How do I update the file to remove this?

**Comment by technicalpickles** [comment]
We are actually moving away from adding scripts to repository in favor of separate npm packages per scripts. We have already stopped accepting new scripts, and will stop accepting pull requests on this repository after hubot 3.0.

See #1113 for details. If you are interested in maintaining this longer term, check npm in case someone already made a package for it, and if not, check out https://hubot.github.com/docs/scripting/ for creating a package of your own.
