### ISSUE TITLE
github-pull-request-notifier should support new issues filed as well as new pull requests (since they are very similar in Github's API)

### ISSUE THREAD

**Issue by dbkaplun** [github/hubot-scripts#1615]

**Comment by bkeepers** [comment]
Hi @dbkaplun, thanks for the feature request. This repository is actually deprecated (see https://github.com/github/hubot-scripts/issues/1113) and we won't be making any enhancements to the scripts here. You're welcome to use the existing github-pull-request-notifier script as a starting point and publish a new package with the features you want. Let me know if you have any questions.
