### ISSUE TITLE
TeamCity Script Help

### ISSUE THREAD

**Issue by alexcurtin** [github/hubot-scripts#1631]
I am trying to make a TeamCity script that lets our developers more easily deploy a build than the existing teamcity.coffee script in the repo. I want a build ID # to be mapped to a easy project name, like "web" or "database". Below is the script so far, but no luck. I am getting [Wed Apr 08 2015 00:18:02 GMT+0000 (UTC)] ERROR TypeError: undefined is not a function at the @ sign.

```coffeescript
# Description:
#    wrapper for TeamCity REST API for deployments
#
# Dependencies:
#    "underscore": "1.3.3"
#
# Configuration:
#    HUBOT_TEAMCITY_USERNAME = <user name>
#    HUBOT_TEAMCITY_PASSWORD = <password>
#    HUBOT_TEAMCITY_HOSTNAME = <host : port>
#    HUBOT_TEAMCITY_SCHEME = <http || https> defaults to http if not set.
#
# Commands:
#    hubot deploy <project> - Deploy project named <project>
#    hubot deploy branch <project> - Deploy branch project named <project>
#
# Author:
#    Kevin Van Heusen

util                    = require 'util'
_                       = require 'underscore'

console.log "1"
module.exports = (robot) ->
  username = process.env.HUBOT_TEAMCITY_USERNAME
  password = process.env.HUBOT_TEAMCITY_PASSWORD
  hostname = process.env.HUBOT_TEAMCITY_HOSTNAME
  scheme = process.env.HUBOT_TEAMCITY_SCHEME || "http"
  base_url = "#{scheme}://#{hostname}"
  # trunk TC deploy projects - map of friendly alias to TC build ID
  trunkProjectMap =
      'cloud': 'bt88'
      'db': 'bt89'
      'database': 'bt89'
  # branch TC deploy projects - map of friendly alias to TC build ID
  branchProjectMap =
      'cloud': 'branch1'
      'db': 'branch2'
      'database': 'branch2'
  # Deploy the correct builds
  deploy: (msg = {}, map = {}) ->
      projectName = msg.match[1]
      if projectName == "all"
          for key, value of map
              @add2Queue(msg, projectName, value)
      else
          for key, value of map
              @add2Queue(msg, projectName, value) if key == projectName
      return true

  # Add to deploy queue
  add2Queue: (msg, projectName, buildId) ->
      url = "#{base_url}/httpAuth/action.html?add2Queue=#{buildId}"
      headers = Authorization: "Basic #{new Buffer("#{username}:#{password}").toString("base64")}", Accept: "application/json"
      msg.http(url)
          .headers(headers)
          .get() (err, res, body) ->
              if res.statusCode == 200
                  msg.send("Deploying #{projectName}")
              else
                  msg.send("Fail! Something went wrong. Couldn't start the build for some reason. Build Id is #{buildId}")
      return true

  # Deploy
  robot.respond /deploy (.*)/i, (msg) ->
    @deploy(msg, @trunkProjectMap)
  robot.respond /deploy branch (.*)/i, (msg) ->
    @deploy(msg, @branchProjectMap)
```

**Comment by technicalpickles** [comment]
> I am getting [Wed Apr 08 2015 00:18:02 GMT+0000 (UTC)] ERROR TypeError: undefined is not a function at the @ sign.

`@` refers to `this` in coffeescript, and in this case, you aren't putting them on an object. So, you can just remove the `@` and it should work.

**Comment by ajcurtin** [comment]
remove the @ before deploy and my mappings (@trunkProjectMap) and (@branchProjectMap)?

**Comment by ajcurtin** [comment]
removing that I know get the error: (UTC)] ERROR ReferenceError: deploy is not defined

**Comment by technicalpickles** [comment]
> remove the @ before deploy and my mappings (@trunkProjectMap) and (@branchProjectMap)?

That'd be my take, yes.

> removing that I now get the error: (UTC)] ERROR ReferenceError: deploy is not defined

Try running `coffee path/to/script`. That should try to load the file and give you a better stacktrace. It'd be helpful to paste your new code, or update the issue body as well.

**Comment by ajcurtin** [comment]
Hi Mr Pickles! Thanks for your prompt reply. Here is the full code. I am perhaps not using a key value map correctly in Coffee but logically it seems there. Thanks a ton :)

# Description:
#    wrapper for TeamCity REST API for deployments
#
# Dependencies:
#    "underscore": "1.3.3"
#
# Configuration:
#    HUBOT_TEAMCITY_USERNAME = <user name>
#    HUBOT_TEAMCITY_PASSWORD = <password>
#    HUBOT_TEAMCITY_HOSTNAME = <host : port>
#    HUBOT_TEAMCITY_SCHEME = <http || https> defaults to http if not set.
#
# Commands:
#    hubot deploy <project> - Deploy project named <project>
#    hubot deploy branch <project> - Deploy branch project named <project>
#
# Author:
#    Kevin Van Heusen

util                    = require 'util'
_                       = require 'underscore'

console.log "1"
module.exports = (robot) ->
  username = process.env.HUBOT_TEAMCITY_USERNAME
  password = process.env.HUBOT_TEAMCITY_PASSWORD
  hostname = process.env.HUBOT_TEAMCITY_HOSTNAME
  scheme = process.env.HUBOT_TEAMCITY_SCHEME || "http"
  base_url = "#{scheme}://#{hostname}"
  # trunk TC deploy projects - map of friendly alias to TC build ID
  trunkProjectMap =
      'cloud': 'bt88'
      'db': 'bt89'
      'database': 'bt89'
  # branch TC deploy projects - map of friendly alias to TC build ID
  branchProjectMap =
      'cloud': 'branch1'
      'db': 'branch2'
      'database': 'branch2'
  # Deploy the correct builds
  deploy: (msg = {}, map = {}) ->
      projectName = msg.match[1]
      if projectName == "all"
          for key, value of map
              @add2Queue(msg, projectName, value)
      else
          for key, value of map
              @add2Queue(msg, projectName, value) if key == projectName
      return true

  # Add to deploy queue
  add2Queue: (msg, projectName, buildId) ->
      url = "#{base_url}/httpAuth/action.html?add2Queue=#{buildId}"
      headers = Authorization: "Basic #{new Buffer("#{username}:#{password}").toString("base64")}", Accept: "application/json"
      msg.http(url)
          .headers(headers)
          .get() (err, res, body) ->
              if res.statusCode == 200
                  msg.send("Deploying #{projectName}")
              else
                  msg.send("Fail! Something went wrong. Couldn't start the build for some reason. Build Id is #{buildId}")
      return true

  # Deploy
  robot.respond /deploy (.*)/i, (msg) ->
    deploy(msg, trunkProjectMap)
  robot.respond /deploy branch (.*)/i, (msg) ->
    deploy(msg, branchProjectMap)

**Comment by technicalpickles** [comment]
I think this is the problem:

```
deploy: (msg = {}, map = {}) ->
```

That's using a object literal, so it's an object that has `deploy: <function>`. This should fix it:

```
deploy = (msg = {}, map = {}) ->
```

**Comment by ajcurtin** [comment]
Hi Mr Pickles,

I tried that change and am getting this in the console.log:

 at process._tickCallback (node.js:355:11)
2015-04-09T18:36:50.612467+00:00 app[web.1]: [Thu Apr 09 2015 18:36:50 GMT+0000 (UTC)] ERROR TypeError: undefined is not a function
2015-04-09T18:36:50.612475+00:00 app[web.1]:   at TextListener.callback (/app/scripts/teamcity.coffee:66:5, <js>:70:14)

line 66:5 is right where deploy(msg, trunkProjectMap) starts, at the "deploy" part.

**Comment by technicalpickles** [comment]
@ajcurtin looks like the same problem you had for deploy is happening for branchProjectMap and trunkProjectMap

**Comment by ajcurtin** [comment]
in that case, am I just mapping this incorrectly? I can start from scratch but I need the ability to map and then pass that mapping to the #{buildID}. branchProjectMap and trunkProjectMap has been defined with an = so i'm out of ideas - maybe ill start all over.

**Comment by technicalpickles** [comment]
We are actually moving away from adding scripts to repository in favor of separate npm packages per scripts. We have already stopped accepting new scripts, and will stop accepting pull requests on this repository after hubot 3.0.

See #1113 for details. If you are interested in maintaining this longer term, check npm in case someone already made a package for it, and if not, check out https://hubot.github.com/docs/scripting/ for creating a package of your own.

cc @assaf @lukesmith @felipecsl @micahlmartin @jan0sch @apolishch and @dalini as contributors to this script.
