### ISSUE TITLE
Help with 9gag script

### ISSUE THREAD

**Issue by davoz96** [github/hubot-scripts#1635]
Hi, i use hubot with the telegram adapter (hubot-tg). 
9gag.coffee just link a random 9gag link, but i'd like to make it automatically download the image and send it to the origin (for visibility). Is it possible?

**Comment by bkeepers** [comment]
Hi @davoz96, hubot only returns a link to the image. It's up to the chat client to decide how to handle it. Most chat clients will detect that it is a URL to an image and display it, so maybe you want to pass that along as a feature request to the telegram crew.
