### ISSUE TITLE
Review hubot-scripts organization and npm for scripts that have been extracted

### ISSUE THREAD

**Issue by technicalpickles** [github/hubot-scripts#1641]
As part of deprecating this repo, we'll want to find scripts that have been extracted, and prompt users to use those. When we get closer to turning this off, we can make it more forceful.

Some places to look:
- https://github.com/hubot-scripts
- https://github.com/hubot-scripts/packages/issues?q=is%3Aissue+is%3Aclosed
- `npm search hubot-scripts`

~~Example snippet for deprecation: https://github.com/github/hubot-scripts/blob/master/src/scripts/pagerduty.coffee#L61~~ (This is handled in hubot as of 2.19.0)

Running list of things to deprecate:
- [x] `9gag`: https://github.com/luijose/hubot-9gag
- [x] `asana`: https://github.com/hubot-scripts/hubot-asana
- [x] `ascii`: https://github.com/sanderploegsma/hubot-ascii-art
- [x] `banbang`: https://www.npmjs.com/package/hubot-bang-bang
- [x] `coin`: https://github.com/fordnox/hubot-coin
- [x] `darksky`: https://github.com/hubot-scripts/hubot-darksky
- [x] `factoids`: https://github.com/hubot-scripts/hubot-factoids
- [x] `gitlab` for https://github.com/spruce/hubot-gitlab-hooks
- [x] `google`: for https://github.com/mnpk/hubot-google
- [x] `isup`: https://github.com/pric/hubot-isup
- [x] `jenkins`: https://github.com/balbeko/hubot-jenkins
- [x] `jira-issues`:  https://github.com/rustedgrail/hubot-jira
- [x] `karma`: https://github.com/notpeter/hubot-karma-classic
- [x] `meme_captain.coffee`: cycomachead/hubot-meme
- [x] resumator: https://github.com/ChrisMissal/hubot-resumator
- [x] wolfram: https://github.com/notpeter/hubot-wolfram
- [x] xkcd.coffee: https://www.npmjs.com/package/hubot-xkcd
- [x] youtube-info: https://github.com/ClaudeBot/hubot-youtube-info
- [x] s3-brain.coffee:  https://github.com/dylanmei/hubot-s3-brain
- [x] shipit.coffee: https://github.com/hubot-scripts/hubot-shipit
- [ ] aww: https://github.com/thejefe/hubot-aww

Known things without extractions:
- [ ] bing.coffee
- [ ] bang-bang.coffee
- [ ] python_library.coffee
- [ ] cowsay.coffee
- [ ] brewerydb.coffee (there's a npm package, but the GitHub repository was deleted, and README makes it look like it was something else)
- [ ] github-pulls.coffee
- [ ] graphite.coffee

cc @github/open-source-hubot-maintainers

**Comment by technicalpickles** [comment]
When new issues are opened, we should check to see if it's on a script that's been extracted. That'd give us a nice reactive list, without having to go through everything up front.

**Comment by notpeter** [comment]
I'm also maintaining the original Karma script (karma.coffee, not plusplus.coffee).
https://github.com/notpeter/hubot-karma-classic

**Comment by cycomachead** [comment]
I'm willing to move my package over to wherever it needs to be. I'm also probably going to work on my own hubot over the summer and will probably find reasons to fix scripts -- what should the process be for doing that? It seems like most scripts have an author, but not necessarily a maintainer, assuming I give credit to the original work, is there any harm in creating a new package, and the creating new PR's with deprecation warnings?

**Comment by cycomachead** [comment]
Some additional scripts to deprecate:

meme_captain.coffee → cycomachead/hubot-meme
xkcd.coffee → https://www.npmjs.com/package/hubot-xkcd

**Comment by ChrisMissal** [comment]
I moved [resumator.coffee](https://github.com/github/hubot-scripts/blob/88649da75ff8fc8af36b7e07c3dcd0a03faa1d45/src/scripts/resumator.coffee) to it's own repo here: https://github.com/ChrisMissal/hubot-resumator

**Comment by technicalpickles** [comment]
github/hubot-scripts#1697 adds a mapping of deprecated scripts in that package to external packages. Then github/hubot#970 builds on this to display notices to users that they are using the deprecated thing with some actions to take. Unfortunately, the action for most people is going to be to try to find a replacement or maintain it themself, but the notice points to this issue for coordination.

**Comment by khera** [comment]
I was just directed here after an npm update and restart of my hubot. One of the scripts the warning message says has no replacement is "s3-brain.coffee", yet I see it linked above in the checklist. Is it supposed to detect these already, or is that still not an implemented feature?

**Comment by jvarness** [comment]
@technicalpickles for brewerydb.coffee, I made a hubot package that uses untappd instead of brewerydb that can suggest random beers for you: https://github.com/jvarness/hubot-barkeep

This isn't a 100% like-for-like replacement, but it might be similar.

**Comment by jdoose** [comment]
jenkins-notifier -> https://github.com/halkeye/hubot-jenkins-notifier

**Comment by markspolakovs** [comment]
calm-down -> https://www.npmjs.com/package/hubot-calm-down

**Comment by mmwtsn** [comment]
redis-brain -> https://github.com/hubot-scripts/hubot-redis-brain

**Comment by iserko** [comment]
bitcoin -> https://www.npmjs.com/package/hubot-bitcoin
days_since -> https://www.npmjs.com/package/hubot-days_since
redis-brain -> https://www.npmjs.com/package/hubot-redis-brain 
spotify -> https://www.npmjs.com/package/hubot-spotify
