### ISSUE TITLE
Syntax Error: Octal Literal error - "todo" does NOT work.

### ISSUE THREAD

**Issue by dylanh724** [github/hubot-scripts#1645]
http://i.imgur.com/YkpwPF8.png
Syntax Error: octal literal '0076' must be prefixed with '0o'

Seems that the script isn't critical - it does NOT crash, however, only "todo users" will work. todo does NOT work.

**Comment by technicalpickles** [comment]
Looks like the [asana script](https://github.com/github/hubot-scripts/blob/master/src/scripts/asana.coffee).   This repository has been deprecated for awhile in favor of npm packages, and it looks like this one was extracted to https://github.com/hubot-scripts/hubot-asana . I'd give that a try to see if it works any better.

**Comment by technicalpickles** [comment]
cc https://github.com/github/hubot-scripts/issues/1641 for details on the deprecation
