### ISSUE TITLE
Factoid not saving facts

### ISSUE THREAD

**Issue by dylanh724** [github/hubot-scripts#1646]
Not sure if I'm doing this wrong, but
~test is a testing value
<nothing happens>
factoids list
<nothing happens>

...?

**Comment by bkeepers** [comment]
Hi @dylanh724, can you confirm that factoid is in `hubot-scripts.json` and when you ask `hubot help factoid` it shows up?

**Comment by technicalpickles** [comment]
This repository has been [deprecated](https://github.com/github/hubot-scripts/issues/1641) for awhile in favor of npm packages, and it looks like this one was extracted to https://github.com/hubot-scripts/hubot-factoid . I'd give that a try to see if it works any better.

**Comment by bkeepers** [comment]
Oops, repo is actually at https://github.com/hubot-scripts/hubot-factoids (plural)
