### ISSUE TITLE
memecaptain v1API is gone

### ISSUE THREAD

**Issue by peelman** [github/hubot-scripts#1648]
The v1 API is gone and while [v2 seems to be a thing](https://twitter.com/memecaptain/status/610294975130013697), my node-fu has been unable to get it working. With the current repo version, Hubot just responds with:

> Sorry, I couldn't generate that meme. Unexpected status from memecaption.com: 404

There's been at least one guy who's [gotten it to work](https://twitter.com/ericjsilva/status/611311883778457600), but he hasn't published his changes yet (that I can tell).

**Comment by technicalpickles** [comment]
We are actually moving away from adding scripts to repository in favor of separate npm packages per scripts. We have already stopped accepting new scripts, and will stop accepting pull requests on this repository after hubot 3.0.

See #1113 for details. If you are interested in maintaining this longer term, check npm in case someone already made a package for it, and if not, check out https://hubot.github.com/docs/scripting/ for creating a package of your own.

**Comment by cycomachead** [comment]
I just published `hubot-meme` which updates this script! :)

Feel free to grab it! It should be a drop-in replacement, except for the iron price meme which I didn't get around to figuring out how to upload a new image yet...

@technicalpickles I can take over the deprecation for the old script -- but since it's entirely broken - is it worth submitting a PR w/ new code? (though that doesn't encourage people to leave this repo...)

**Comment by ericjsilva** [comment]
I also created a PR to use the old script, https://github.com/github/hubot-scripts/pull/1649. I maintain my own copy of the script with custom meme images, but I added the important bits to the PR.

**Comment by cycomachead** [comment]
@ericjsilva Do you mind if I integrate your changes into the hubot-meme package I'm working on?

**Comment by peelman** [comment]
@cycomachead I was going to do it and do a pull request, but if you wanna beat me to it I'm not going to argue :)

**Comment by cycomachead** [comment]
I'm probably not going to have a chance for a few hours so if you have free time, go for it! 

-- 
Michael Ball
From my iPhone
michaelballphoto.com

**Comment by michaelansel** [comment]
:heart: Thanks for taking care of this, y'all!

**Comment by peelman** [comment]
In lieu of #1649 I'm closing this.

@cycomachead I won't have time until mid-morning tomorrow; but I'm totally fine with doing it and sending you a PR when its done.

**Comment by ericjsilva** [comment]
@cycomachead @peelman I have no issues with either of you snagging the code and using it wherever you need to. Let me know if you have issues. I'd be glad to help.

**Comment by phillc** [comment]
I meant to respond to this a long time ago, I took the work from meme captain and removed external services as a dependency to it: https://github.com/phillc/hubot-hosted-memes
