### ISSUE TITLE
cleverbot stopped working

### ISSUE THREAD

**Issue by trashken** [github/hubot-scripts#1653]
keeps returning 404 errors..

**Comment by technicalpickles** [comment]
We're actually in the progress of deprecating this repository in favor of separate repositories for each script over at https://github.com/github/hubot-scripts/issues/1641. If you are using the script, and would be willing to help maintain it as it's own thing, that'd be super helpful :grin: 

cc @ajacksified as the original contributor of this script

**Comment by trashken** [comment]
Yes I'm using this script. Will take a look at #1641.

**Comment by MrMMorris** [comment]
@ajacksified would love to see the cleverbot script working! currently, I just get `<html>`

**Comment by scarolan** [comment]
Same here.  Cleverbot just throws a 404 error now.

**Comment by technicalpickles** [comment]
https://github.com/github/hubot-scripts/pull/1659 might fix this

**Comment by ajacksified** [comment]
Sorry I missed this - I can pull it out to a separate repo if you haven't already, and upgrade cleverbot.
