### ISSUE TITLE
Jenkins says: Status 404 <html>

### ISSUE THREAD

**Issue by swaroopkundeti** [github/hubot-scripts#1662]
Hi,

I have jenkins jobs configured in separate folder. So in this I could pull the discription/last with hubot but unable to build the job. Below the logs which might help for describing this issue.

<pre>

Describe job:

Slack logs:

hubot jenkins describe Synduit/job/Build QA

JOB: Build QA
URL: http://ci.synduit4.com/job/Synduit/job/Build%20QA/
ENABLED: true
STATUS: blue
HEALTH: 
 Build stability: No recent builds failed.

Nginx logs:
[19/Aug/2015:17:11:59 +0000] "GET /job/Synduit/job/Build%20QA/api/json HTTP/1.1" 200 9480 "-" "Hubot/2.13.2"
[19/Aug/2015:17:11:59 +0000] "GET /job/Synduit/job/Build%20QA/api/json HTTP/1.1" 200 9480 "-" "Hubot/2.13.2"

Building Jobs:

Slack logs:

hubot jenkins build Synduit/job/Build QA

 Jenkins says: Status 404 <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /job/synduit/build. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                     

Nginx Logs:

[19/Aug/2015:17:19:12 +0000] "POST /job/Synduit/build HTTP/1.1" 404 1382 "-" "Hubot/2.13.2"

</pre>

**Comment by technicalpickles** [comment]
We have been slowly deprecating this repository over in https://github.com/github/hubot-scripts/issues/1641 . This particular script was extracted to https://github.com/balbeko/hubot-jenkins. Would you be able to try that and see if it helps? If not, you can file issues over on that repository.
