### ISSUE TITLE
Add ids to scripts?

### ISSUE THREAD

**Issue by wsoula** [github/hubot-scripts#1663]
With https://github.com/github/hubot/pull/803 merged should ids be added to the scripts so they can be turned off and on with https://github.com/kristenmills/hubot-command-blacklist?  If so what would be the format of the ids added?  I needed to turn off image me and animate me so I changed them to have the id image.me and animate.me, we could do something like that.  I'm happy to help if this change is deemed appropriate.

**Comment by michaelansel** [comment]
Yes, this is definitely something we want to do. PRs are welcome with nicely namespaced listener IDs (e.g. `google.image.static`, `google.image.animated`, `google.image.corgi`). The most important consideration with the IDs is that they be globally unique and consistent even if the message pattern changes.

**Comment by technicalpickles** [comment]
It'd be good in general, but it is a lot of work, and this repository is deprecated. Considering we are trying to move scripts out of it (https://github.com/github/hubot-scripts/issues/1641), I think the time would be better spent updating scripts in whatever repository they end up extracted to.
