### ISSUE TITLE
Pinboard.coffee script

### ISSUE THREAD

**Issue by RickCogley** [github/hubot-scripts#1673]
Hello - I notice the pinboard.coffee script has not been migrated to the new way of doing things. 

It does still work if you use the old method of calling it, but, how can I assist to migrate it? Or, is this something the original author has to do?

**Comment by technicalpickles** [comment]
@RickCogley here's the approach I usually take:

* google for the hubot package name to see if someone else has ported it, but hasn't updated it
* if it hasn't been ported, start a new repo for it, check the history for contributors. ping them in an issue on the repo if they'd still use it and would want to contribute to it (or take over the repo).
