### ISSUE TITLE
Connect to Jenkins via CAS

### ISSUE THREAD

**Issue by vwbusguy** [github/hubot-scripts#1674]
The hubot Jenkins plugin is highly useful, but becomes unusable when integrating Jenkins with CAS for authentication, as hubot will be redirected to the CAS login page and then fail.  

However, there are a handful of nodejs CAS authentication clients that we could use.  I'm more familiar with the python, java, and php CAS client implementations, but it should nonetheless be possible to support this.

The difficulty is that using CAS credentials are given by redirecting a user to login page and storing a subsequent cookie on the app side.  For this to work with hubot we would need to automate the login process on the CAS side and present the cookie in the header to Jenkins on the request.  Here's an example: https://gist.github.com/dodok1/4134605

**Comment by technicalpickles** [comment]
We are in the [process of deprecating this repository](https://github.com/github/hubot-scripts/issues/1641), and encouraging people to use npm packages instead. If you are referring to jenkins.coffee, there is a package now at  https://github.com/balbeko/hubot-jenkins you can try.
