### ISSUE TITLE
how to send data in  http Get request

### ISSUE THREAD

**Issue by maneeshmp** [github/hubot-scripts#1680]
I am trying to write postgre puppet AST query in coffee script so i can automate it through hubot, but I am not able to figure out how to send data (curl -d) through a GET request coffree scripts. Can anyone help?

I wrote a hubot script like this

```
https = require('https')
fs = require('fs')
options =
  key: fs.readFileSync('hubotkey.pem')
  cert: fs.readFileSync('hubotcert.pem')
  ca: fs.readFileSync('hubotca.pem')
  hostname: 'puppet.abc.com'
  port: 8081
  path: '/pdb/query/v4/reports'
  data: 'query=["extract", ["hash", "end_time", "certname", "status", "noop", "configuration_version", "environment"], ["and", ["=", "status", "failed"],["and", [">", "end_time", "2015-11-11T21:59:48.130Z"]]]]'
module.exports = (robot) ->
  robot.respond /puppet fail/i, (msg) ->
    data = []
    https.get(options, (res) ->
      console.log res.statusCode
      if res.statusCode == 200
        res.on 'data', (chunk) ->
          data.push(chunk)
          console.log chunk
        res.on 'end', () ->
          parsedData = JSON.parse(data.join(''))
          console.log parsedData
          dt = JSON.stringify(parsedData)
          console.log dt
          msg.send(dt)
    )
```

but this doesn't work at all. 

The below curl command works just fine.

    curl -X GET http://puppet.abc.com:8081/pdb/query/v4/reports -d 'query=["extract", ["hash", "end_time", "certname", "status", "noop", "metrics", "configuration_version", "environment"], ["and", ["=", "status", "failed"], ["and", ["=", "latest_report?",true]]]]'

Can anyone help by giving a pointer ?

**Comment by technicalpickles** [comment]
Hubot includes an http library to make it easier. Check out the scripting guide with examples: https://github.com/github/hubot/blob/master/docs/scripting.md#making-http-calls

I don't usually use nodejs's `https`, but I don't see anything obviously missing with the code snippet you included. It's not really specific to hubot though, so you should be able to find some examples of doing http gets.

I'd also suggest checking the logs of whatever is on the other end of the http request if you have access to them. That might give you insight into what is being sent across the line (if anything).
