### ISSUE TITLE
ASCII script is broken

### ISSUE THREAD

**Issue by sanderploegsma** [github/hubot-scripts#1685]
The heroku app used to create the ASCII message is down: http://asciime.herokuapp.com/

**Comment by sanderploegsma** [comment]
For future users, check [this script](https://github.com/sanderploegsma/hubot-ascii-art) using figlet.

**Comment by technicalpickles** [comment]
Thanks for putting that package together!

This repository has been [deprecated](https://github.com/github/hubot-scripts/issues/1113) for awhile in favor of npm packages. We are in the process of finding scripts that have been extracted, and deprecating them over in https://github.com/github/hubot-scripts/issues/1641 so I added this script to the list.
