### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by arminhaghi** [github/hubot-scripts#1688]
Two of the images in the script are returning 404 now.

http://img70.imageshack.us/img70/4853/cutesquirrels27rn9.jpg
http://img70.imageshack.us/img70/9615/cutesquirrels15ac7.jpg

**Comment by parkr** [comment]
Fixed by #1687.

**Comment by ralt** [comment]
@parkr #1687 wasn't merged though

**Comment by kotnik** [comment]
It is proposed now in non-deprecated repo: https://github.com/hubot-scripts/hubot-shipit/pull/14
