### ISSUE TITLE
Hubot - Unexpected MATH when adding custom scripts

### ISSUE THREAD

**Issue by DannyWatson23** [github/hubot-scripts#1691]
I wanted to simply add a line to hubot's `example.coffee` script that simply said: 

```
robot.hear/who do you fight for?/i, (res) ->
res.send "I fight for the users!"

```

but whenever I boot it up via campfire, it is throwing me these errors about unexpected MATH, why the hell is it trying to do math on a simple statement? I see no numerical equations in that statement. What is going on?

` ERROR Unable to load /home/hubot/scripts/Hubot: SyntaxError: unexpected MATH`
``

**Comment by technicalpickles** [comment]
@DannyWatson23 This repository is for hubot-scripts, which is a specific package, and [is actually deprecated](https://github.com/github/hubot-scripts). Sounds like you have having a general problem with hubot, so github.com/github/hubot would be a better place to ask.

To answer your question, I see two problem: there needs to be a space between `hear` and the `/`, and `res.send` needs to be indented.

**Comment by jm** [comment]
@DannyWatson23 I think I see the problem that you likely already found:

```
robot.hear/who do you fight for?/i
```

Note the lack of space between `hear` and `who`, so it probably thinks you're trying to divide those?  Not sure if that's it or not, but seems likely.
