### ISSUE TITLE
isup: ERROR SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by tchncs** [github/hubot-scripts#1703]
```
[Sun Jun 05 2016 23:36:55 GMT+0200 (CEST)] ERROR SyntaxError: Unexpected end of JSON input
at Object.parse (native)
at /node_modules/hubot-scripts/src/scripts/isup.coffee:25:23
at IncomingMessage.<anonymous> (/node_modules/scoped-http-client/src/index.js:95:22)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:926:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)
```
Latest official hubot version, latest hubot-scripts.

**Comment by parkr** [comment]
If you're able to print the return value from the API, that would be great. It looks like you're getting some non-JSON response. Occasionally error pages are HTML.

**Comment by tchncs** [comment]
It should be like:

```
{
https://isitup.org/duckduckgo.com.json ->
 
   "domain": "duckduckgo.com",
    "port": 80,
    "status_code": 1,
    "response_ip": "54.229.105.92",
    "response_code": 200,
    "response_time": 0.023
}
```
shouldn't it?

I dont know how to extract it, here is the debug log:

```
DEBUG Received message: purrbot, is https://duckduckgo.com up? in room: undefined, from: illuna. Private chat JID is ...
DEBUG Message 'purrbot, is https://duckduckgo.com up?' matched regex //(http(?:s?):\/\/(\S*))/i/; listener.options = { id: null }
DEBUG Executing listener callback for Message 'purrbot, is https://duckduckgo.com up?'
DEBUG Message 'purrbot, is https://duckduckgo.com up?' matched regex //^\s*[@]?purrbot[:,]?\s*(?:is (?:http\:\/\/)?(.*?) (up|down)(\?)?)/i/; listener.options = { id: null }
DEBUG Executing listener callback for Message 'purrbot, is https://duckduckgo.com up?'
ERROR SyntaxError: Unexpected end of JSON input
```

**Comment by jonfairbanks** [comment]
The issue seems to be here: 

`msg.http("http://isitup.org/#{domain}.json")
    .header('User-Agent', 'Hubot')
    .get() (err, res, body)`

"body" will be undefined here and does not contain JSON data. This leads to JSON.parse failing. 

To fix, need to replace this HTTP get method with a different method to get JSON data from the endpoint.

**Comment by technicalpickles** [comment]
We are in the [process of deprecating this repository](https://github.com/github/hubot-scripts/issues/1641). We're not accepting any changes or fixing any issues unless it furthers that end. If anyone is interested in taking the isup script and repackaging it with fixes, I'd strongly encourage it.

There is a https://www.npmjs.com/package/hubot-isup but the repository is gone, and it doesn't seem to use isitup.org
