### ISSUE TITLE
howdoi.coffee

### ISSUE THREAD

**Issue by greenlighttec** [github/hubot-scripts#1721]
This script doesn't apper to function and I can't find out why yet :/

**Comment by hashashin** [comment]
@greenlighttec the problem it's their dependence: scraper. You need to use [gargsms/node-scraper](https://github.com/gargsms/node-scraper) instead, "```npm install -S gargsms/node-scraper```" will do the job.
Or you can install the fork I made: [hubot-howdoi](https://www.npmjs.com/package/hubot-howdoi), which you can install via npm as usual.

**Comment by greenlighttec** [comment]
@hashashin worked perfectly thank you!
