### ISSUE TITLE
Nick Presta wrote a duplicate of slothme

### ISSUE THREAD

**Issue by kaneda** [github/hubot-scripts#1733]
Not sure why @nickpresta would do such a thing instead of using the existing plugin

https://www.npmjs.com/package/hubot-slothme

**Comment by nickpresta** [comment]
Not really sure what this issue is about. I wrote the initial script over 4 years ago: https://github.com/github/hubot-scripts/commit/994e94a58b2a9c6658dc98daf84aa9c1fecda568

This may have been a duplicate at the time but the PR was accepted and the project you linked to seems months old. 

???
